"""Render research tables from verified counts; no saved-rate transcription."""

from .replay import BUDGET_KEYS
from ._aggregate_reference import REQUESTED_TIERS


def percent(value):
    return "undefined" if value is None else f"{value * 100:.4f}%"


def render(result):
    locked = result["evaluations"]["LOCKED_TEST"]
    lines = [
        "# GoEmotions MB1 — regenerated evidence tables", "",
        "Generated by `uqrc goemotions` from the verified evidence bundle. These are retrospective benchmark results, not product certification or a rerun of model training.", "",
        f"Evidence manifest SHA-256: `{result['evidence_manifest_sha256']}`.", "",
        "## Final calibration and locked observations", "",
        "Calibration uses 5,426 comments; locked evaluation uses 10,853. Each risk budget has delta 0.05 separately. Locked error rates are descriptive; no joint four-budget or subgroup guarantee is claimed.", "",
        "| Budget | Threshold | Calibration selected / unsupported | CP upper | Tests / passing | Locked selected / unsupported | Automation | Selected error | Review |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for key in BUDGET_KEYS:
        cal, row = result["final_controllers"][key], locked["controllers"][key]
        lines.append(f"| {float(key):.0%} | {cal['threshold']!r} | {cal['selected']} / {cal['harmful']} | {percent(cal['cp_upper'])} | {cal['tested']} / {cal['certified']} | {row['selected']} / {row['harmful']} | {percent(row['automation'])} | {percent(row['selected_error'])} | {percent(row['review_rate'])} |")
    lines += ["", "The 5% and 10% policies automate fewer than 5% of locked comments. Higher budgets expand automation alongside more unsupported tags. These results concern agreement with the annotation reference, not a person's actual emotional state.", "", "## Executed calibration tests", "", "Only the historical executed prefix is replayed for each budget. The last row for each budget is its first failure; the seven candidates beyond the longest executed prefix are not tested.", "", "| Budget | Sequence index (0-based) | Threshold | Selected | Unsupported | Exact p-value | Pass |", "| --- | --- | --- | --- | --- | --- | --- |"]
    for key in BUDGET_KEYS:
        for row in result["candidate_tests"][key]:
            lines.append(f"| {float(key):.0%} | {row['index']} | {row['threshold']!r} | {row['selected']} | {row['harmful']} | {row['p_value']:.12g} | {'yes' if row['passes'] else 'no'} |")
    lines += ["", "## Locked baselines", "", "Raw-confidence policies are descriptive comparators with no formal calibration claim. Review-all has undefined conditional error.", "", "| Policy | Selected | Unsupported | Automation | Selected error | Review |", "| --- | --- | --- | --- | --- | --- |"]
    for key in ("REVIEW_ALL", "ACCEPT_ALL_TOP_TAGS", "RAW_CONFIDENCE_GE_0_5", "RAW_CONFIDENCE_GE_0_8", "RAW_CONFIDENCE_GE_0_9"):
        row = locked["baselines"][key]
        lines.append(f"| {key} | {row['selected']} | {row['harmful']} | {percent(row['automation'])} | {percent(row['selected_error'])} | {percent(row['review_rate'])} |")
    lines += ["", "## Warm-up sample-size summaries", "", "Each non-full tier has 100 recorded whole-group-prefix samples. Realized sizes can be smaller than requested. FULL uses the complete 5,427-comment pool once. Frequencies and quantiles are regenerated from 2,804 aggregate records; sampling orders and the candidate tests within each warm-up run are not replayed.", "", "| Budget | Requested n | Realized n range | Certification frequency | Median automation | Automation p05–p95 | Runs with selections | Median selected error (nonzero runs) |", "| --- | --- | --- | --- | --- | --- | --- | --- |"]
    for key in BUDGET_KEYS:
        for tier in (*REQUESTED_TIERS, "FULL"):
            row = result["warmup"][key]["aggregates"][str(tier)]
            a, e = row["evaluation_automation"], row["evaluation_selected_error_nonzero"]
            lines.append(f"| {float(key):.0%} | {tier} | {row['realized_n']['min']}–{row['realized_n']['max']} | {percent(row['certification_frequency'])} | {percent(a['median'])} | {percent(a['p05'])}–{percent(a['p95'])} | {e['runs']} | {percent(e['median'])} |")
    lines += ["", "## Locked consensus strata", "", "Consensus strength is maximum label votes divided by number of raters: high ≥0.80, medium ≥0.60 and <0.80, low <0.60. These slices are descriptive.", "", "| Budget | Stratum | N | Selected | Unsupported | Automation | Selected error |", "| --- | --- | --- | --- | --- | --- | --- |"]
    for key in BUDGET_KEYS:
        for name in ("HIGH_CONSENSUS", "MEDIUM_CONSENSUS", "LOW_CONSENSUS"):
            row = locked["consensus"][key][name]
            lines.append(f"| {float(key):.0%} | {name} | {row['n']} | {row['selected']} | {row['harmful']} | {percent(row['automation'])} | {percent(row['selected_error'])} |")
    lines += ["", "## Locked predicted-emotion slices", "", "The historical reporting floor is 30 selected comments. Denominators and selected counts are retained below that floor, while unsupported counts and error rates remain unreported. Missing values are not filled with zero. No per-emotion guarantee is claimed.", "", "| Budget | Predicted emotion | Predicted N | Selected | Unsupported | Automation | Selected error |", "| --- | --- | --- | --- | --- | --- | --- |"]
    for key in BUDGET_KEYS:
        for name, row in sorted(locked["predicted_emotion"][key].items()):
            h = row["harmful"] if row["adequate_selected_n"] else "not reported"
            error = percent(row["selected_error"]) if row["adequate_selected_n"] else "not reported"
            lines.append(f"| {float(key):.0%} | {name} | {row['n']} | {row['selected']} | {h} | {percent(row['automation'])} | {error} |")
    lines += ["", "## Development history", "", "D1's original confidence-derived risk score returned review-all on the full warm-up pool. D1R's exploratory candidate/order refinement remained unsupported and reused warm-up calibration information. D1S added a development-only logistic meta-risk model and obtained formal but very low automation. MB1 retained the D1S scorer and sequence, then used separate final-calibration and locked roles.", "", "| Phase | Recorded evidence |", "| --- | --- |"]
    history = result["development_history"]
    for name in ("D1", "D1R"):
        row = history[name]["first_test"]
        lines.append(f"| {name} | First test: {row['selected']} selected, {row['harmful']} unsupported, p={row['p_value']:.12g}, CP upper={percent(row['cp_upper'])}; fails at 5%. |")
    row = history["D1S"]["evaluation"]
    lines.append(f"| D1S | Warm-up evaluation: {row['selected']} selected, {row['harmful']} unsupported out of {row['n']}; automation={percent(row['selected']/row['n'])}. |")
    lines += ["", "## Interpretation limits", "", "The formal unit is a comment. Group-preserving splits reduce obvious leakage but do not establish independent Bernoulli observations. Annotation disagreement, the English Reddit population, development reuse, and possible dependence limit interpretation. The private historical freeze record is not public preregistration or independent verification of its timing.", "", "This report regenerates aggregate evidence and replays final candidate tests. It does not reconstruct raw annotations, refit the classifier/meta-model, reproduce historical sampling orders, or run checkpoint inference. See the study reproduction document for the exact scope and unresolved assignment dependency.", ""]
    return "\n".join(lines)
